# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a35tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/mxwang/Project/FPGA/ARTY100T/verilog-ethernet/example/Arty/fpga/fpga/fpga.cache/wt [current_project]
set_property parent.project_path /home/mxwang/Project/FPGA/ARTY100T/verilog-ethernet/example/Arty/fpga/fpga/fpga.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  /home/mxwang/Project/FPGA/ARTY100T/verilog-ethernet/example/Arty/fpga/lib/eth/lib/axis/rtl/arbiter.v
  /home/mxwang/Project/FPGA/ARTY100T/verilog-ethernet/example/Arty/fpga/lib/eth/rtl/arp.v
  /home/mxwang/Project/FPGA/ARTY100T/verilog-ethernet/example/Arty/fpga/lib/eth/rtl/arp_cache.v
  /home/mxwang/Project/FPGA/ARTY100T/verilog-ethernet/example/Arty/fpga/lib/eth/rtl/arp_eth_rx.v
  /home/mxwang/Project/FPGA/ARTY100T/verilog-ethernet/example/Arty/fpga/lib/eth/rtl/arp_eth_tx.v
  /home/mxwang/Project/FPGA/ARTY100T/verilog-ethernet/example/Arty/fpga/lib/eth/lib/axis/rtl/axis_async_fifo.v
  /home/mxwang/Project/FPGA/ARTY100T/verilog-ethernet/example/Arty/fpga/lib/eth/lib/axis/rtl/axis_async_fifo_adapter.v
  /home/mxwang/Project/FPGA/ARTY100T/verilog-ethernet/example/Arty/fpga/lib/eth/lib/axis/rtl/axis_fifo.v
  /home/mxwang/Project/FPGA/ARTY100T/verilog-ethernet/example/Arty/fpga/lib/eth/rtl/axis_gmii_rx.v
  /home/mxwang/Project/FPGA/ARTY100T/verilog-ethernet/example/Arty/fpga/lib/eth/rtl/axis_gmii_tx.v
  /home/mxwang/Project/FPGA/ARTY100T/verilog-ethernet/example/Arty/fpga/rtl/debounce_switch.v
  /home/mxwang/Project/FPGA/ARTY100T/verilog-ethernet/example/Arty/fpga/lib/eth/rtl/eth_arb_mux.v
  /home/mxwang/Project/FPGA/ARTY100T/verilog-ethernet/example/Arty/fpga/lib/eth/rtl/eth_axis_rx.v
  /home/mxwang/Project/FPGA/ARTY100T/verilog-ethernet/example/Arty/fpga/lib/eth/rtl/eth_axis_tx.v
  /home/mxwang/Project/FPGA/ARTY100T/verilog-ethernet/example/Arty/fpga/lib/eth/rtl/eth_mac_1g.v
  /home/mxwang/Project/FPGA/ARTY100T/verilog-ethernet/example/Arty/fpga/lib/eth/rtl/eth_mac_mii.v
  /home/mxwang/Project/FPGA/ARTY100T/verilog-ethernet/example/Arty/fpga/lib/eth/rtl/eth_mac_mii_fifo.v
  /home/mxwang/Project/FPGA/ARTY100T/verilog-ethernet/example/Arty/fpga/rtl/fpga.v
  /home/mxwang/Project/FPGA/ARTY100T/verilog-ethernet/example/Arty/fpga/rtl/fpga_core.v
  /home/mxwang/Project/FPGA/ARTY100T/verilog-ethernet/example/Arty/fpga/lib/eth/rtl/ip.v
  /home/mxwang/Project/FPGA/ARTY100T/verilog-ethernet/example/Arty/fpga/lib/eth/rtl/ip_arb_mux.v
  /home/mxwang/Project/FPGA/ARTY100T/verilog-ethernet/example/Arty/fpga/lib/eth/rtl/ip_complete.v
  /home/mxwang/Project/FPGA/ARTY100T/verilog-ethernet/example/Arty/fpga/lib/eth/rtl/ip_eth_rx.v
  /home/mxwang/Project/FPGA/ARTY100T/verilog-ethernet/example/Arty/fpga/lib/eth/rtl/ip_eth_tx.v
  /home/mxwang/Project/FPGA/ARTY100T/verilog-ethernet/example/Arty/fpga/lib/eth/rtl/lfsr.v
  /home/mxwang/Project/FPGA/ARTY100T/verilog-ethernet/example/Arty/fpga/lib/eth/rtl/mii_phy_if.v
  /home/mxwang/Project/FPGA/ARTY100T/verilog-ethernet/example/Arty/fpga/lib/eth/lib/axis/rtl/priority_encoder.v
  /home/mxwang/Project/FPGA/ARTY100T/verilog-ethernet/example/Arty/fpga/lib/eth/rtl/ssio_sdr_in.v
  /home/mxwang/Project/FPGA/ARTY100T/verilog-ethernet/example/Arty/fpga/lib/eth/lib/axis/rtl/sync_reset.v
  /home/mxwang/Project/FPGA/ARTY100T/verilog-ethernet/example/Arty/fpga/rtl/sync_signal.v
  /home/mxwang/Project/FPGA/ARTY100T/verilog-ethernet/example/Arty/fpga/lib/eth/rtl/udp.v
  /home/mxwang/Project/FPGA/ARTY100T/verilog-ethernet/example/Arty/fpga/lib/eth/rtl/udp_checksum_gen.v
  /home/mxwang/Project/FPGA/ARTY100T/verilog-ethernet/example/Arty/fpga/lib/eth/rtl/udp_complete.v
  /home/mxwang/Project/FPGA/ARTY100T/verilog-ethernet/example/Arty/fpga/lib/eth/rtl/udp_ip_rx.v
  /home/mxwang/Project/FPGA/ARTY100T/verilog-ethernet/example/Arty/fpga/lib/eth/rtl/udp_ip_tx.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/mxwang/Project/FPGA/ARTY100T/verilog-ethernet/example/Arty/fpga/fpga.xdc
set_property used_in_implementation false [get_files /home/mxwang/Project/FPGA/ARTY100T/verilog-ethernet/example/Arty/fpga/fpga.xdc]

read_xdc -unmanaged /home/mxwang/Project/FPGA/ARTY100T/verilog-ethernet/example/Arty/fpga/lib/eth/syn/mii_phy_if.tcl
set_property used_in_implementation false [get_files /home/mxwang/Project/FPGA/ARTY100T/verilog-ethernet/example/Arty/fpga/lib/eth/syn/mii_phy_if.tcl]

read_xdc -unmanaged /home/mxwang/Project/FPGA/ARTY100T/verilog-ethernet/example/Arty/fpga/lib/eth/syn/eth_mac_fifo.tcl
set_property used_in_implementation false [get_files /home/mxwang/Project/FPGA/ARTY100T/verilog-ethernet/example/Arty/fpga/lib/eth/syn/eth_mac_fifo.tcl]

read_xdc -unmanaged /home/mxwang/Project/FPGA/ARTY100T/verilog-ethernet/example/Arty/fpga/lib/eth/lib/axis/syn/axis_async_fifo.tcl
set_property used_in_implementation false [get_files /home/mxwang/Project/FPGA/ARTY100T/verilog-ethernet/example/Arty/fpga/lib/eth/lib/axis/syn/axis_async_fifo.tcl]

read_xdc -unmanaged /home/mxwang/Project/FPGA/ARTY100T/verilog-ethernet/example/Arty/fpga/lib/eth/lib/axis/syn/sync_reset.tcl
set_property used_in_implementation false [get_files /home/mxwang/Project/FPGA/ARTY100T/verilog-ethernet/example/Arty/fpga/lib/eth/lib/axis/syn/sync_reset.tcl]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top fpga -part xc7a35tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef fpga.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file fpga_utilization_synth.rpt -pb fpga_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
